=== psws/ContestViewer/QCountries.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="QCountries" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="QCountries">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="ID" index-key="ID " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="Prefix" index-key="Prefix " primary="no" unique="yes" clustered="no" order="asc"/>
<od:index index-name="PrimaryKey" index-key="ID " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAABBcPMe820VTZJB1QPyQ2rjAAAAAA8ahe1SwONAAAAAAAAAAABRAEMA
bwB1AG4AdAByAGkAZQBzAAAAAAAAAMaQ/8JmtZVBoIp1aD6Ysc8HAAAAQXDzHvNt
FU2SQdUD8kNq40kARAAAAAAAAACNPSzlfm/ISrj0li/1TaAtBwAAAEFw8x7zbRVN
kkHVA/JDauNQAHIAZQBmAGkAeAAAAAAAAABcPAVFzTTeR4N8S6wYZOYWBwAAAEFw
8x7zbRVNkkHVA/JDauNOAGEAbQBlAAAA
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="GUID" type="9" value="QXDzHvNtFU2SQdUD8kNq4w==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="ID" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="1"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="GUID" type="9" value="xpD/wma1lUGginVoPpixzw==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Prefix" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="GUID" type="9" value="jT0s5X5vyEq49JYv9U2gLQ==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="6"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Name" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="1740"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="GUID" type="9" value="XDwFRc003keDfEusGGTmFg==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="16"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== psws/ContestViewer/QCountries.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="QCountries.xsd" generated="2015-08-08T22:30:31">
<QCountries>
<ID>1</ID>
<Prefix>LU</Prefix>
<Name>Argentina</Name>
</QCountries>
<QCountries>
<ID>2</ID>
<Prefix>VP5</Prefix>
<Name>Turks &amp; Caicos</Name>
</QCountries>
<QCountries>
<ID>3</ID>
<Prefix>HI</Prefix>
<Name>Dominican Republ</Name>
</QCountries>
<QCountries>
<ID>4</ID>
<Prefix>VE</Prefix>
<Name>Canada</Name>
</QCountries>
<QCountries>
<ID>5</ID>
<Prefix>K</Prefix>
<Name>United States</Name>
</QCountries>
<QCountries>
<ID>6</ID>
<Prefix>KP2</Prefix>
<Name>Virgin Is.</Name>
</QCountries>
<QCountries>
<ID>7</ID>
<Prefix>PJ2</Prefix>
<Name>Netherlands Anti</Name>
</QCountries>
<QCountries>
<ID>8</ID>
<Prefix>FY</Prefix>
<Name>French Guiana</Name>
</QCountries>
<QCountries>
<ID>9</ID>
<Prefix>EA</Prefix>
<Name>Spain</Name>
</QCountries>
<QCountries>
<ID>10</ID>
<Prefix>DL</Prefix>
<Name>Germany</Name>
</QCountries>
<QCountries>
<ID>11</ID>
<Prefix>LA</Prefix>
<Name>Norway</Name>
</QCountries>
<QCountries>
<ID>12</ID>
<Prefix>OZ</Prefix>
<Name>Denmark</Name>
</QCountries>
<QCountries>
<ID>13</ID>
<Prefix>GM</Prefix>
<Name>Scotland</Name>
</QCountries>
<QCountries>
<ID>14</ID>
<Prefix>PA</Prefix>
<Name>Netherlands</Name>
</QCountries>
<QCountries>
<ID>15</ID>
<Prefix>ON</Prefix>
<Name>Belgium</Name>
</QCountries>
<QCountries>
<ID>16</ID>
<Prefix>F</Prefix>
<Name>France</Name>
</QCountries>
<QCountries>
<ID>17</ID>
<Prefix>SM</Prefix>
<Name>Sweden</Name>
</QCountries>
<QCountries>
<ID>18</ID>
<Prefix>HB0</Prefix>
<Name>Liechtenstein</Name>
</QCountries>
<QCountries>
<ID>19</ID>
<Prefix>YL</Prefix>
<Name>Latvia</Name>
</QCountries>
<QCountries>
<ID>20</ID>
<Prefix>S5</Prefix>
<Name>Slovenia</Name>
</QCountries>
<QCountries>
<ID>21</ID>
<Prefix>OK</Prefix>
<Name>Czech Republic</Name>
</QCountries>
<QCountries>
<ID>22</ID>
<Prefix>GI</Prefix>
<Name>Northern Ireland</Name>
</QCountries>
<QCountries>
<ID>23</ID>
<Prefix>GW</Prefix>
<Name>Wales</Name>
</QCountries>
<QCountries>
<ID>24</ID>
<Prefix>OE</Prefix>
<Name>Austria</Name>
</QCountries>
<QCountries>
<ID>25</ID>
<Prefix>LY</Prefix>
<Name>Lithuania</Name>
</QCountries>
<QCountries>
<ID>26</ID>
<Prefix>G</Prefix>
<Name>England</Name>
</QCountries>
<QCountries>
<ID>27</ID>
<Prefix>OM</Prefix>
<Name>Slovakia</Name>
</QCountries>
<QCountries>
<ID>28</ID>
<Prefix>SV9</Prefix>
<Name>Crete</Name>
</QCountries>
<QCountries>
<ID>29</ID>
<Prefix>HA</Prefix>
<Name>Hungary</Name>
</QCountries>
<QCountries>
<ID>30</ID>
<Prefix>YU</Prefix>
<Name>Serbia</Name>
</QCountries>
<QCountries>
<ID>31</ID>
<Prefix>CT3</Prefix>
<Name>Madeira Is.</Name>
</QCountries>
<QCountries>
<ID>32</ID>
<Prefix>6Y</Prefix>
<Name>Jamaica</Name>
</QCountries>
<QCountries>
<ID>33</ID>
<Prefix>9A</Prefix>
<Name>Croatia</Name>
</QCountries>
<QCountries>
<ID>34</ID>
<Prefix>I</Prefix>
<Name>Italy</Name>
</QCountries>
<QCountries>
<ID>35</ID>
<Prefix>UR</Prefix>
<Name>Ukraine</Name>
</QCountries>
<QCountries>
<ID>36</ID>
<Prefix>IT9</Prefix>
<Name>Sicily</Name>
</QCountries>
<QCountries>
<ID>37</ID>
<Prefix>ES</Prefix>
<Name>Estonia</Name>
</QCountries>
<QCountries>
<ID>38</ID>
<Prefix>VP2E</Prefix>
<Name>Anguilla</Name>
</QCountries>
<QCountries>
<ID>39</ID>
<Prefix>YN</Prefix>
<Name>Nicaragua</Name>
</QCountries>
<QCountries>
<ID>40</ID>
<Prefix>UA</Prefix>
<Name>European Russia</Name>
</QCountries>
<QCountries>
<ID>41</ID>
<Prefix>4O</Prefix>
<Name>Montenegro</Name>
</QCountries>
<QCountries>
<ID>42</ID>
<Prefix>YO</Prefix>
<Name>Romania</Name>
</QCountries>
<QCountries>
<ID>43</ID>
<Prefix>OH</Prefix>
<Name>Finland</Name>
</QCountries>
<QCountries>
<ID>44</ID>
<Prefix>CT</Prefix>
<Name>Portugal</Name>
</QCountries>
<QCountries>
<ID>45</ID>
<Prefix>E7</Prefix>
<Name>Bosnia-Herzegovi</Name>
</QCountries>
<QCountries>
<ID>46</ID>
<Prefix>EA6</Prefix>
<Name>Balearic Is.</Name>
</QCountries>
<QCountries>
<ID>47</ID>
<Prefix>IS</Prefix>
<Name>Sardinia</Name>
</QCountries>
<QCountries>
<ID>48</ID>
<Prefix>3V</Prefix>
<Name>Tunisia</Name>
</QCountries>
<QCountries>
<ID>49</ID>
<Prefix>HB</Prefix>
<Name>Switzerland</Name>
</QCountries>
<QCountries>
<ID>50</ID>
<Prefix>9Y</Prefix>
<Name>Trinidad &amp; Tobag</Name>
</QCountries>
<QCountries>
<ID>51</ID>
<Prefix>LZ</Prefix>
<Name>Bulgaria</Name>
</QCountries>
<QCountries>
<ID>52</ID>
<Prefix>C3</Prefix>
<Name>Andorra</Name>
</QCountries>
<QCountries>
<ID>53</ID>
<Prefix>SP</Prefix>
<Name>Poland</Name>
</QCountries>
<QCountries>
<ID>54</ID>
<Prefix>UA2</Prefix>
<Name>Kaliningrad</Name>
</QCountries>
<QCountries>
<ID>55</ID>
<Prefix>5B</Prefix>
<Name>Cyprus</Name>
</QCountries>
<QCountries>
<ID>56</ID>
<Prefix>UA9</Prefix>
<Name>Asiatic Russia</Name>
</QCountries>
<QCountries>
<ID>57</ID>
<Prefix>EU</Prefix>
<Name>Belarus</Name>
</QCountries>
<QCountries>
<ID>58</ID>
<Prefix>ER</Prefix>
<Name>Moldova</Name>
</QCountries>
<QCountries>
<ID>59</ID>
<Prefix>Z3</Prefix>
<Name>Macedonia</Name>
</QCountries>
<QCountries>
<ID>60</ID>
<Prefix>6W</Prefix>
<Name>Senegal</Name>
</QCountries>
<QCountries>
<ID>61</ID>
<Prefix>SV5</Prefix>
<Name>Dodecanese</Name>
</QCountries>
<QCountries>
<ID>62</ID>
<Prefix>UN</Prefix>
<Name>Kazakhstan</Name>
</QCountries>
<QCountries>
<ID>63</ID>
<Prefix>PY</Prefix>
<Name>Brazil</Name>
</QCountries>
<QCountries>
<ID>64</ID>
<Prefix>CN</Prefix>
<Name>Morocco</Name>
</QCountries>
<QCountries>
<ID>65</ID>
<Prefix>TA</Prefix>
<Name>Turkey</Name>
</QCountries>
<QCountries>
<ID>66</ID>
<Prefix>OH0</Prefix>
<Name>Aland Is.</Name>
</QCountries>
<QCountries>
<ID>67</ID>
<Prefix>SV</Prefix>
<Name>Greece</Name>
</QCountries>
<QCountries>
<ID>68</ID>
<Prefix>D4</Prefix>
<Name>Cape Verde</Name>
</QCountries>
<QCountries>
<ID>69</ID>
<Prefix>V4</Prefix>
<Name>St. Kitts &amp; Nevi</Name>
</QCountries>
<QCountries>
<ID>70</ID>
<Prefix>JA</Prefix>
<Name>Japan</Name>
</QCountries>
<QCountries>
<ID>71</ID>
<Prefix>KH6</Prefix>
<Name>Hawaii</Name>
</QCountries>
<QCountries>
<ID>72</ID>
<Prefix>ZS</Prefix>
<Name>South Africa</Name>
</QCountries>
<QCountries>
<ID>73</ID>
<Prefix>5Z</Prefix>
<Name>Kenya</Name>
</QCountries>
<QCountries>
<ID>74</ID>
<Prefix>A7</Prefix>
<Name>Qatar</Name>
</QCountries>
<QCountries>
<ID>75</ID>
<Prefix>V5</Prefix>
<Name>Namibia</Name>
</QCountries>
<QCountries>
<ID>76</ID>
<Prefix>EA8</Prefix>
<Name>Canary Is.</Name>
</QCountries>
<QCountries>
<ID>77</ID>
<Prefix>HZ</Prefix>
<Name>Saudi Arabia</Name>
</QCountries>
<QCountries>
<ID>78</ID>
<Prefix>5R</Prefix>
<Name>Madagascar</Name>
</QCountries>
<QCountries>
<ID>79</ID>
<Prefix>4X</Prefix>
<Name>Israel</Name>
</QCountries>
<QCountries>
<ID>80</ID>
<Prefix>3DA</Prefix>
<Name>Swaziland</Name>
</QCountries>
<QCountries>
<ID>81</ID>
<Prefix>YB</Prefix>
<Name>Indonesia</Name>
</QCountries>
<QCountries>
<ID>82</ID>
<Prefix>A4</Prefix>
<Name>Oman</Name>
</QCountries>
<QCountries>
<ID>83</ID>
<Prefix>EK</Prefix>
<Name>Armenia</Name>
</QCountries>
<QCountries>
<ID>84</ID>
<Prefix>HS</Prefix>
<Name>Thailand</Name>
</QCountries>
<QCountries>
<ID>85</ID>
<Prefix>9K</Prefix>
<Name>Kuwait</Name>
</QCountries>
<QCountries>
<ID>86</ID>
<Prefix>CX</Prefix>
<Name>Uruguay</Name>
</QCountries>
<QCountries>
<ID>87</ID>
<Prefix>SU</Prefix>
<Name>Egypt</Name>
</QCountries>
<QCountries>
<ID>88</ID>
<Prefix>5H</Prefix>
<Name>Tanzania</Name>
</QCountries>
<QCountries>
<ID>89</ID>
<Prefix>ZP</Prefix>
<Name>Paraguay</Name>
</QCountries>
<QCountries>
<ID>90</ID>
<Prefix>ET</Prefix>
<Name>Ethiopia</Name>
</QCountries>
<QCountries>
<ID>91</ID>
<Prefix>VK</Prefix>
<Name>Australia</Name>
</QCountries>
<QCountries>
<ID>92</ID>
<Prefix>EX</Prefix>
<Name>Kyrgyzstan</Name>
</QCountries>
<QCountries>
<ID>93</ID>
<Prefix>TY</Prefix>
<Name>Benin</Name>
</QCountries>
<QCountries>
<ID>94</ID>
<Prefix>4L</Prefix>
<Name>Georgia</Name>
</QCountries>
<QCountries>
<ID>95</ID>
<Prefix>T8</Prefix>
<Name>Palau</Name>
</QCountries>
<QCountries>
<ID>96</ID>
<Prefix>BY</Prefix>
<Name>China</Name>
</QCountries>
<QCountries>
<ID>97</ID>
<Prefix>VU</Prefix>
<Name>India</Name>
</QCountries>
<QCountries>
<ID>98</ID>
<Prefix>BV</Prefix>
<Name>Taiwan</Name>
</QCountries>
<QCountries>
<ID>99</ID>
<Prefix>XU</Prefix>
<Name>Kampuchea</Name>
</QCountries>
<QCountries>
<ID>100</ID>
<Prefix>HL</Prefix>
<Name>South Korea</Name>
</QCountries>
<QCountries>
<ID>101</ID>
<Prefix>KH2</Prefix>
<Name>Guam</Name>
</QCountries>
<QCountries>
<ID>102</ID>
<Prefix>9V</Prefix>
<Name>Singapore</Name>
</QCountries>
<QCountries>
<ID>103</ID>
<Prefix>LX</Prefix>
<Name>Luxembourg</Name>
</QCountries>
<QCountries>
<ID>104</ID>
<Prefix>VR</Prefix>
<Name>Hong Kong</Name>
</QCountries>
<QCountries>
<ID>105</ID>
<Prefix>TA1</Prefix>
<Name>Turkey (Europe)</Name>
</QCountries>
<QCountries>
<ID>106</ID>
<Prefix>9H</Prefix>
<Name>Malta</Name>
</QCountries>
<QCountries>
<ID>107</ID>
<Prefix>EI</Prefix>
<Name>Ireland</Name>
</QCountries>
<QCountries>
<ID>108</ID>
<Prefix>A9</Prefix>
<Name>Bahrain</Name>
</QCountries>
<QCountries>
<ID>109</ID>
<Prefix>J8</Prefix>
<Name>St. Vincent</Name>
</QCountries>
<QCountries>
<ID>110</ID>
<Prefix>DU</Prefix>
<Name>Philippines</Name>
</QCountries>
<QCountries>
<ID>111</ID>
<Prefix>VU4</Prefix>
<Name>Andaman &amp; Nicoba</Name>
</QCountries>
<QCountries>
<ID>112</ID>
<Prefix>9M6</Prefix>
<Name>East Malaysia</Name>
</QCountries>
<QCountries>
<ID>113</ID>
<Prefix>HK</Prefix>
<Name>Colombia</Name>
</QCountries>
<QCountries>
<ID>114</ID>
<Prefix>KP4</Prefix>
<Name>Puerto Rico</Name>
</QCountries>
<QCountries>
<ID>115</ID>
<Prefix>3A</Prefix>
<Name>Monaco</Name>
</QCountries>
<QCountries>
<ID>116</ID>
<Prefix>YV</Prefix>
<Name>Venezuela</Name>
</QCountries>
<QCountries>
<ID>117</ID>
<Prefix>FM</Prefix>
<Name>Martinique</Name>
</QCountries>
<QCountries>
<ID>118</ID>
<Prefix>TZ</Prefix>
<Name>Mali</Name>
</QCountries>
<QCountries>
<ID>119</ID>
<Prefix>XE</Prefix>
<Name>Mexico</Name>
</QCountries>
<QCountries>
